import 'package:shared_preferences/shared_preferences.dart';

class Data {
  static var lsLesson = {
    "People": {
      "selected": true,
      "lsWord": {
        "1 [one]": "0001",
        "People": "0002",
        "I": "0003",
        "I and you": "0004",
        "both of us": "0005",
        "he": "0006",
        "he and she": "0007",
        "they both": "0008",
        "the man": "0009",
        "the woman": "0010",
        "the child": "0011",
        "a family": "0012",
        "my family": "0013",
        "My family is here.": "0014",
        "I am here.": "0015",
        "You are here. (singular)": "0016",
        "He is here and she is here.": "0017",
        "We are here.": "0018",
        "You are here. (plurial)": "0019",
        "They are all here.": "0020",
      },
    },
    "Family Members": {
      "selected": false,
      "lsWord": {
        "2 [two]": "0021",
        "Family Members": "0022",
        "the grandfather": "0023",
        "the grandmother": "0024",
        "the father": "0026",
        "the mother": "0027",
        "the son": "0029",
        "the daughter": "0030",
        "the brother": "0032",
        "the sister": "0033",
        "the uncle": "0035",
        "the aunt": "0036",
        "We are a family.": "0038",
        "The family is not small.": "0039",
        "The family is big.": "0040",
      },
    },
    "Getting to know others": {
      "selected": false,
      "lsWord": {
        "3 [three]": "0041",
        "Getting to know others": "0042",
        "Hi!": "0043",
        "Hello!": "0044",
        "How are you?": "0045",
        "Do you come from Europe?": "0046",
        "Do you come from America?": "0047",
        "Do you come from Asia?": "0048",
        "In which hotel are you staying?": "0049",
        "How long have you been here for?": "0050",
        "How long will you be staying?": "0051",
        "Do you like it here?": "0052",
        "Are you here on vacation?": "0053",
        "Please do visit me sometime!": "0054",
        "Here is my address.": "0055",
        "Shall we see each other tomorrow?": "0056",
        "I am sorry, but I already have plans.": "0057",
        "Bye!": "0058",
        "Good bye!": "0059",
        "See you soon!": "0060",
      },
    },
    "At school": {
      "selected": false,
      "lsWord": {
        "4 [four]": "0061",
        "At school": "0062",
        "Where are we?": "0063",
        "We are at school.": "0064",
        "We are having class / a lesson.": "0065",
        "Those are the school children.": "0066",
        "That is the teacher.": "0067",
        "That is the class.": "0068",
        "What are we doing?": "0069",
        "We are learning.": "0070",
        "We are learning a language.": "0071",
        "I learn English.": "0072",
        "You learn Spanish.": "0073",
        "He learns German.": "0074",
        "We learn French.": "0075",
        "You all learn Italian.": "0076",
        "They learn Russian.": "0077",
        "Learning languages is interesting.": "0078",
        "We want to understand people.": "0079",
        "We want to speak with people.": "0080",
      },
    },
    "Countries and Languages": {
      "selected": false,
      "lsWord": {
        "5 [five]": "0081",
        "Countries and Languages": "0082",
        "John is from London.": "0083",
        "London is in Great Britain.": "0084",
        "He speaks English.": "0085",
        "Maria is from Madrid.": "0086",
        "Madrid is in Spain.": "0087",
        "She speaks Spanish.": "0088",
        "Peter and Martha are from Berlin.": "0089",
        "Berlin is in Germany.": "0090",
        "Do both of you speak German?": "0091",
        "London is a capital city.": "0092",
        "Madrid and Berlin are also capital cities.": "0093",
        "Capital cities are big and noisy.": "0094",
        "France is in Europe.": "0095",
        "Egypt is in Africa.": "0096",
        "Japan is in Asia.": "0097",
        "Canada is in North America.": "0098",
        "Panama is in Central America.": "0099",
        "Brazil is in South America.": "0100",
      },
    },
    "Reading and writing": {
      "selected": false,
      "lsWord": {
        "6 [six]": "0101",
        "Reading and writing": "0102",
        "I read.": "0103",
        "I read a letter (character).": "0104",
        "I read a word.": "0105",
        "I read a sentence.": "0106",
        "I read a letter.": "0107",
        "I read a book.": "0108",
        "You read.": "0110",
        "He reads.": "0111",
        "I write.": "0112",
        "I write a letter (character).": "0113",
        "I write a word.": "0114",
        "I write a sentence.": "0115",
        "I write a letter.": "0116",
        "I write a book.": "0117",
        "You write.": "0119",
        "He writes.": "0120",
      },
    },
    "Numbers": {
      "selected": false,
      "lsWord": {
        "7 [seven]": "0121",
        "Numbers": "0122",
        "I count:": "0123",
        "one, two, three": "0124",
        "I count to three.": "0125",
        "I count further:": "0126",
        "four, five, six,": "0127",
        "seven, eight, nine": "0128",
        "I count.": "0129",
        "You count.": "0130",
        "He counts.": "0131",
        "One. The first.": "0132",
        "Two. The second.": "0133",
        "Three. The third.": "0134",
        "Four. The fourth.": "0135",
        "Five. The fifth.": "0136",
        "Six. The sixth.": "0137",
        "Seven. The seventh.": "0138",
        "Eight. The eighth.": "0139",
        "Nine. The ninth.": "0140",
      },
    },
    "The time": {
      "selected": false,
      "lsWord": {
        "8 [eight]": "0141",
        "The time": "0142",
        "Excuse me!": "0143",
        "What time is it, please?": "0144",
        "Thank you very much.": "0145",
        "It is one o�clock.": "0146",
        "It is two o�clock.": "0147",
        "It is three o�clock.": "0148",
        "It is four o�clock.": "0149",
        "It is five o�clock.": "0150",
        "It is six o�clock.": "0151",
        "It is seven o�clock.": "0152",
        "It is eight o�clock.": "0153",
        "It is nine o�clock.": "0154",
        "It is ten o�clock.": "0155",
        "It is eleven o�clock.": "0156",
        "It is twelve o�clock.": "0157",
        "A minute has sixty seconds.": "0158",
        "An hour has sixty minutes.": "0159",
        "A day has twenty-four hours.": "0160",
      },
    },
    "Days of the week": {
      "selected": false,
      "lsWord": {
        "9 [nine]": "0161",
        "Days of the week": "0162",
        "Monday": "0163",
        "Tuesday": "0164",
        "Wednesday": "0165",
        "Thursday": "0166",
        "Friday": "0167",
        "Saturday": "0168",
        "Sunday": "0169",
        "the week": "0170",
        "from Monday to Sunday": "0171",
        "The first day is Monday.": "0172",
        "The second day is Tuesday.": "0173",
        "The third day is Wednesday.": "0174",
        "The fourth day is Thursday.": "0175",
        "The fifth day is Friday.": "0176",
        "The sixth day is Saturday.": "0177",
        "The seventh day is Sunday.": "0178",
        "The week has seven days.": "0179",
        "We only work for five days.": "0180",
      },
    },
    "Yesterday � today � tomorrow": {
      "selected": false,
      "lsWord": {
        "10 [ten]": "0181",
        "Yesterday � today � tomorrow": "0182",
        "Yesterday was Saturday.": "0183",
        "I was at the cinema yesterday.": "0184",
        "The film was interesting.": "0185",
        "Today is Sunday.": "0186",
        "I�m not working today.": "0187",
        "I�m staying at home.": "0188",
        "Tomorrow is Monday.": "0189",
        "Tomorrow I will work again.": "0190",
        "I work at an office.": "0191",
        "Who is that?": "0192",
        "That is Peter.": "0193",
        "Peter is a student.": "0194",
        "That is Martha.": "0196",
        "Martha is a secretary.": "0197",
        "Peter and Martha are friends.": "0198",
        "Peter is Martha�s friend.": "0199",
        "Martha is Peter�s friend.": "0200",
      },
    },
    "Months": {
      "selected": false,
      "lsWord": {
        "11 [eleven]": "0201",
        "Months": "0202",
        "January": "0203",
        "February": "0204",
        "March": "0205",
        "April": "0206",
        "May": "0207",
        "June": "0208",
        "These are six months.": "0209",
        "January, February, March,": "0210",
        "April, May and June.": "0211",
        "July": "0212",
        "August": "0213",
        "September": "0214",
        "October": "0215",
        "November": "0216",
        "December": "0217",
        "These are also six months.": "0218",
        "July, August, September,": "0219",
        "October, November and December.": "0220",
      },
    },
    "Beverages": {
      "selected": false,
      "lsWord": {
        "12 [twelve]": "0221",
        "Beverages": "0222",
        "I drink tea.": "0223",
        "I drink coffee.": "0224",
        "I drink mineral water.": "0225",
        "Do you drink tea with lemon?": "0226",
        "Do you drink coffee with sugar?": "0227",
        "Do you drink water with ice?": "0228",
        "There is a party here.": "0229",
        "People are drinking champagne.": "0230",
        "People are drinking wine and beer.": "0231",
        "Do you drink alcohol?": "0232",
        "Do you drink whisky / whiskey (am.)?": "0233",
        "Do you drink Coke with rum?": "0234",
        "I do not like champagne.": "0235",
        "I do not like wine.": "0236",
        "I do not like beer.": "0237",
        "The baby likes milk.": "0238",
        "The child likes cocoa and apple juice.": "0239",
        "The woman likes orange and grapefruit juice.": "0240",
      },
    },
    "Activities": {
      "selected": false,
      "lsWord": {
        "13 [thirteen]": "0241",
        "Activities": "0242",
        "What does Martha do?": "0243",
        "She works at an office.": "0244",
        "She works on the computer.": "0245",
        "Where is Martha?": "0246",
        "At the cinema.": "0247",
        "She is watching a film.": "0248",
        "What does Peter do?": "0249",
        "He studies at the university.": "0250",
        "He studies languages.": "0251",
        "Where is Peter?": "0252",
        "At the caf�.": "0253",
        "He is drinking coffee.": "0254",
        "Where do they like to go?": "0255",
        "To a concert.": "0256",
        "They like to listen to music.": "0257",
        "Where do they not like to go?": "0258",
        "To the disco.": "0259",
        "They do not like to dance.": "0260",
      },
    },
    "Colors": {
      "selected": false,
      "lsWord": {
        "14 [fourteen]": "0261",
        "Colors": "0262",
        "Snow is white.": "0263",
        "The sun is yellow.": "0264",
        "The orange is orange.": "0265",
        "The cherry is red.": "0266",
        "The sky is blue.": "0267",
        "The grass is green.": "0268",
        "The earth is brown.": "0269",
        "The cloud is grey / gray (am.).": "0270",
        "The tyres / tires (am.) are black.": "0271",
        "What colour / color (am.) is the snow? White.": "0272",
        "What colour / color (am.) is the sun? Yellow.": "0273",
        "What colour / color (am.) is the orange? Orange.": "0274",
        "What colour / color (am.) is the cherry? Red.": "0275",
        "What colour / color (am.) is the sky? Blue.": "0276",
        "What colour / color (am.) is the grass? Green.": "0277",
        "What colour / color (am.) is the earth? Brown.": "0278",
        "What colour / color (am.) is the cloud? Grey / Gray (am.).": "0279",
        "What colour / color (am.) are the tyres / tires (am.)? Black.": "0280",
      },
    },
    "Fruits and food": {
      "selected": false,
      "lsWord": {
        "15 [fifteen]": "0281",
        "Fruits and food": "0282",
        "I have a strawberry.": "0283",
        "I have a kiwi and a melon.": "0284",
        "I have an orange and a grapefruit.": "0285",
        "I have an apple and a mango.": "0286",
        "I have a banana and a pineapple.": "0287",
        "I am making a fruit salad.": "0288",
        "I am eating toast.": "0289",
        "I am eating toast with butter.": "0290",
        "I am eating toast with butter and jam.": "0291",
        "I am eating a sandwich.": "0292",
        "I am eating a sandwich with margarine.": "0293",
        "I am eating a sandwich with margarine and tomatoes.": "0294",
        "We need bread and rice.": "0295",
        "We need fish and steaks.": "0296",
        "We need pizza and spaghetti.": "0297",
        "What else do we need?": "0298",
        "We need carrots and tomatoes for the soup.": "0299",
        "Where is the supermarket?": "0300",
      },
    },
    "Seasons and Weather": {
      "selected": false,
      "lsWord": {
        "16 [sixteen]": "0301",
        "Seasons and Weather": "0302",
        "These are the seasons:": "0303",
        "Spring, summer,": "0304",
        "autumn / fall (am.) and winter.": "0305",
        "The summer is warm.": "0306",
        "The sun shines in summer.": "0307",
        "We like to go for a walk in summer.": "0308",
        "The winter is cold.": "0309",
        "It snows or rains in winter.": "0310",
        "We like to stay home in winter.": "0311",
        "It is cold.": "0312",
        "It is raining.": "0313",
        "It is windy.": "0314",
        "It is warm.": "0315",
        "It is sunny.": "0316",
        "It is pleasant.": "0317",
        "What is the weather like today?": "0318",
        "It is cold today.": "0319",
        "It is warm today.": "0320",
      },
    },
    "Around the house": {
      "selected": false,
      "lsWord": {
        "17 [seventeen]": "0321",
        "Around the house": "0322",
        "Our house is here.": "0323",
        "The roof is on top.": "0324",
        "The basement is below.": "0325",
        "There is a garden behind the house.": "0326",
        "There is no street in front of the house.": "0327",
        "There are trees next to the house.": "0328",
        "My apartment is here.": "0329",
        "The kitchen and bathroom are here.": "0330",
        "The living room and bedroom are there.": "0331",
        "The front door is closed.": "0332",
        "But the windows are open.": "0333",
        "It is hot today.": "0334",
        "We are going to the living room.": "0335",
        "There is a sofa and an armchair there.": "0336",
        "Please, sit down!": "0337",
        "My computer is there.": "0338",
        "My stereo is there.": "0339",
        "The TV set is brand new.": "0340",
      },
    },
    "House cleaning": {
      "selected": false,
      "lsWord": {
        "18 [eighteen]": "0341",
        "House cleaning": "0342",
        "Today is Saturday.": "0343",
        "We have time today.": "0344",
        "We are cleaning the apartment today.": "0345",
        "I am cleaning the bathroom.": "0346",
        "My husband is washing the car.": "0347",
        "The children are cleaning the bicycles.": "0348",
        "Grandma is watering the flowers.": "0349",
        "The children are cleaning up the children�s room.": "0350",
        "My husband is tidying up his desk.": "0351",
        "I am putting the laundry in the washing machine.": "0352",
        "I am hanging up the laundry.": "0353",
        "I am ironing the clothes.": "0354",
        "The windows are dirty.": "0355",
        "The floor is dirty.": "0356",
        "The dishes are dirty.": "0357",
        "Who washes the windows?": "0358",
        "Who does the vacuuming?": "0359",
        "Who does the dishes?": "0360",
      },
    },
    "In the kitchen": {
      "selected": false,
      "lsWord": {
        "19 [nineteen]": "0361",
        "In the kitchen": "0362",
        "Do you have a new kitchen?": "0363",
        "What do you want to cook today?": "0364",
        "Do you cook on an electric or a gas stove?": "0365",
        "Shall I cut the onions?": "0366",
        "Shall I peel the potatoes?": "0367",
        "Shall I rinse the lettuce?": "0368",
        "Where are the glasses?": "0369",
        "Where are the dishes?": "0370",
        "Where is the cutlery / silverware (am.)?": "0371",
        "Do you have a tin opener / can opener (am.)?": "0372",
        "Do you have a bottle opener?": "0373",
        "Do you have a corkscrew?": "0374",
        "Are you cooking the soup in this pot?": "0375",
        "Are you frying the fish in this pan?": "0376",
        "Are you grilling the vegetables on this grill?": "0377",
        "I am setting the table.": "0378",
        "Here are the knives, the forks and the spoons.": "0379",
        "Here are the glasses, the plates and the napkins.": "0380",
      },
    },
    "Small Talk 1": {
      "selected": false,
      "lsWord": {
        "20 [twenty]": "0381",
        "Small Talk 1": "0382",
        "Make yourself comfortable!": "0383",
        "Please, feel right at home!": "0384",
        "What would you like to drink?": "0385",
        "Do you like music?": "0386",
        "I like classical music.": "0387",
        "These are my CD�s.": "0388",
        "Do you play a musical instrument?": "0389",
        "This is my guitar.": "0390",
        "Do you like to sing?": "0391",
        "Do you have children?": "0392",
        "Do you have a dog?": "0393",
        "Do you have a cat?": "0394",
        "These are my books.": "0395",
        "I am currently reading this book.": "0396",
        "What do you like to read?": "0397",
        "Do you like to go to concerts?": "0398",
        "Do you like to go to the theatre / theater (am.)?": "0399",
        "Do you like to go to the opera?": "0400",
      },
    },
    "Small Talk 2": {
      "selected": false,
      "lsWord": {
        "21 [twenty-one]": "0401",
        "Small Talk 2": "0402",
        "Where do you come from?": "0403",
        "From Basel.": "0404",
        "Basel is in Switzerland.": "0405",
        "May I introduce Mr. Miller?": "0406",
        "He is a foreigner.": "0407",
        "He speaks several languages.": "0408",
        "Are you here for the first time?": "0409",
        "No, I was here once last year.": "0410",
        "Only for a week, though.": "0411",
        "How do you like it here?": "0412",
        "A lot. The people are nice.": "0413",
        "And I like the scenery, too.": "0414",
        "What is your profession?": "0415",
        "I am a translator.": "0416",
        "I translate books.": "0417",
        "Are you alone here?": "0418",
        "No, my wife / my husband is also here.": "0419",
        "And those are my two children.": "0420",
      },
    },
    "Small Talk 3": {
      "selected": false,
      "lsWord": {
        "22 [twenty-two]": "0421",
        "Small Talk 3": "0422",
        "Do you smoke?": "0423",
        "I used to.": "0424",
        "But I don�t smoke anymore.": "0425",
        "Does it disturb you if I smoke?": "0426",
        "No, absolutely not.": "0427",
        "It doesn�t disturb me.": "0428",
        "Will you drink something?": "0429",
        "A brandy?": "0430",
        "No, preferably a beer.": "0431",
        "Do you travel a lot?": "0432",
        "Yes, mostly on business trips.": "0433",
        "But now we�re on holiday.": "0434",
        "It�s so hot!": "0435",
        "Yes, today it�s really hot.": "0436",
        "Let�s go to the balcony.": "0437",
        "There�s a party here tomorrow.": "0438",
        "Are you also coming?": "0439",
        "Yes, we�ve also been invited.": "0440",
      },
    },
    "Learning foreign languages": {
      "selected": false,
      "lsWord": {
        "23 [twenty-three]": "0441",
        "Learning foreign languages": "0442",
        "Where did you learn Spanish?": "0443",
        "Can you also speak Portuguese?": "0444",
        "Yes, and I also speak some Italian.": "0445",
        "I think you speak very well.": "0446",
        "The languages are quite similar.": "0447",
        "I can understand them well.": "0448",
        "But speaking and writing is difficult.": "0449",
        "I still make many mistakes.": "0450",
        "Please correct me each time.": "0451",
        "Your pronunciation is very good.": "0452",
        "You only have a slight accent.": "0453",
        "One can tell where you come from.": "0454",
        "What is your mother tongue / native language (am.)?": "0455",
        "Are you taking a language course?": "0456",
        "Which textbook are you using?": "0457",
        "I don�t remember the name right now.": "0458",
        "The title is not coming to me.": "0459",
        "I�ve forgotten it.": "0460",
      },
    },
    "Appointment": {
      "selected": false,
      "lsWord": {
        "24 [twenty-four]": "0461",
        "Appointment": "0462",
        "Did you miss the bus?": "0463",
        "I waited for you for half an hour.": "0464",
        "Don�t you have a mobile / cell phone (am.) with you?": "0465",
        "Be punctual next time!": "0466",
        "Take a taxi next time!": "0467",
        "Take an umbrella with you next time!": "0468",
        "I have the day off tomorrow.": "0469",
        "Shall we meet tomorrow?": "0470",
        "I�m sorry, I can�t make it tomorrow.": "0471",
        "Do you already have plans for this weekend?": "0472",
        "Or do you already have an appointment?": "0473",
        "I suggest that we meet on the weekend.": "0474",
        "Shall we have a picnic?": "0475",
        "Shall we go to the beach?": "0476",
        "Shall we go to the mountains?": "0477",
        "I will pick you up at the office.": "0478",
        "I will pick you up at home.": "0479",
        "I will pick you up at the bus stop.": "0480",
      },
    },
    "In the city": {
      "selected": false,
      "lsWord": {
        "25 [twenty-five]": "0481",
        "In the city": "0482",
        "I would like to go to the station.": "0483",
        "I would like to go to the airport.": "0484",
        "I would like to go to the city centre / center (am.).": "0485",
        "How do I get to the station?": "0486",
        "How do I get to the airport?": "0487",
        "How do I get to the city centre / center (am.)?": "0488",
        "I need a taxi.": "0489",
        "I need a city map.": "0490",
        "I need a hotel.": "0491",
        "I would like to rent a car.": "0492",
        "Here is my credit card.": "0493",
        "Here is my licence / license (am.).": "0494",
        "What is there to see in the city?": "0495",
        "Go to the old city.": "0496",
        "Go on a city tour.": "0497",
        "Go to the harbour / harbor (am.).": "0498",
        "Go on a harbour / harbor (am.) tour.": "0499",
        "Are there any other places of interest?": "0500",
      },
    },
    "In nature": {
      "selected": false,
      "lsWord": {
        "26 [twenty-six]": "0501",
        "In nature": "0502",
        "Do you see the tower there?": "0503",
        "Do you see the mountain there?": "0504",
        "Do you see the village there?": "0505",
        "Do you see the river there?": "0506",
        "Do you see the bridge there?": "0507",
        "Do you see the lake there?": "0508",
        "I like that bird.": "0509",
        "I like that tree.": "0510",
        "I like this stone.": "0511",
        "I like that park.": "0512",
        "I like that garden.": "0513",
        "I like this flower.": "0514",
        "I find that pretty.": "0515",
        "I find that interesting.": "0516",
        "I find that gorgeous.": "0517",
        "I find that ugly.": "0518",
        "I find that boring.": "0519",
        "I find that terrible.": "0520",
      },
    },
    "In the hotel � Arrival": {
      "selected": false,
      "lsWord": {
        "27 [twenty-seven]": "0521",
        "In the hotel � Arrival": "0522",
        "Do you have a vacant room?": "0523",
        "I have booked a room.": "0524",
        "My name is Miller.": "0525",
        "I need a single room.": "0526",
        "I need a double room.": "0527",
        "What does the room cost per night?": "0528",
        "I would like a room with a bathroom.": "0529",
        "I would like a room with a shower.": "0530",
        "Can I see the room?": "0531",
        "Is there a garage here?": "0532",
        "Is there a safe here?": "0533",
        "Is there a fax machine here?": "0534",
        "Fine, I�ll take the room.": "0535",
        "Here are the keys.": "0536",
        "Here is my luggage.": "0537",
        "What time do you serve breakfast?": "0538",
        "What time do you serve lunch?": "0539",
        "What time do you serve dinner?": "0540",
      },
    },
    "In the hotel � Complaints": {
      "selected": false,
      "lsWord": {
        "28 [twenty-eight]": "0541",
        "In the hotel � Complaints": "0542",
        "The shower isn�t working.": "0543",
        "There is no warm water.": "0544",
        "Can you get it repaired?": "0545",
        "There is no telephone in the room.": "0546",
        "There is no TV in the room.": "0547",
        "The room has no balcony.": "0548",
        "The room is too noisy.": "0549",
        "The room is too small.": "0550",
        "The room is too dark.": "0551",
        "The heater isn�t working.": "0552",
        "The air-conditioning isn�t working.": "0553",
        "The TV isn�t working.": "0554",
        "I don�t like that.": "0555",
        "That�s too expensive.": "0556",
        "Do you have anything cheaper?": "0557",
        "Is there a youth hostel nearby?": "0558",
        "Is there a boarding house / a bed and breakfast nearby?": "0559",
        "Is there a restaurant nearby?": "0560",
      },
    },
    "At the restaurant 1": {
      "selected": false,
      "lsWord": {
        "29 [twenty-nine]": "0561",
        "At the restaurant 1": "0562",
        "Is this table taken?": "0563",
        "I would like the menu, please.": "0564",
        "What would you recommend?": "0565",
        "I�d like a beer.": "0566",
        "I�d like a mineral water.": "0567",
        "I�d like an orange juice.": "0568",
        "I�d like a coffee.": "0569",
        "I�d like a coffee with milk.": "0570",
        "With sugar, please.": "0571",
        "I�d like a tea.": "0572",
        "I�d like a tea with lemon.": "0573",
        "I�d like a tea with milk.": "0574",
        "Do you have cigarettes?": "0575",
        "Do you have an ashtray?": "0576",
        "Do you have a light?": "0577",
        "I�m missing a fork.": "0578",
        "I�m missing a knife.": "0579",
        "I�m missing a spoon.": "0580",
      },
    },
    "At the restaurant 2": {
      "selected": false,
      "lsWord": {
        "30 [thirty]": "0581",
        "At the restaurant 2": "0582",
        "An apple juice, please.": "0583",
        "A lemonade, please.": "0584",
        "A tomato juice, please.": "0585",
        "I�d like a glass of red wine.": "0586",
        "I�d like a glass of white wine.": "0587",
        "I�d like a bottle of champagne.": "0588",
        "Do you like fish?": "0589",
        "Do you like beef?": "0590",
        "Do you like pork?": "0591",
        "I�d like something without meat.": "0592",
        "I�d like some mixed vegetables.": "0593",
        "I�d like something that won�t take much time.": "0594",
        "Would you like that with rice?": "0595",
        "Would you like that with pasta?": "0596",
        "Would you like that with potatoes?": "0597",
        "That doesn�t taste good.": "0598",
        "The food is cold.": "0599",
        "I didn�t order this.": "0600",
      },
    },
    "At the restaurant 3": {
      "selected": false,
      "lsWord": {
        "31 [thirty-one]": "0601",
        "At the restaurant 3": "0602",
        "I would like a starter.": "0603",
        "I would like a salad.": "0604",
        "I would like a soup.": "0605",
        "I would like a dessert.": "0606",
        "I would like an ice cream with whipped cream.": "0607",
        "I would like some fruit or cheese.": "0608",
        "We would like to have breakfast.": "0609",
        "We would like to have lunch.": "0610",
        "We would like to have dinner.": "0611",
        "What would you like for breakfast?": "0612",
        "Rolls with jam and honey?": "0613",
        "Toast with sausage and cheese?": "0614",
        "A boiled egg?": "0615",
        "A fried egg?": "0616",
        "An omelette?": "0617",
        "Another yoghurt, please.": "0618",
        "Some salt and pepper also, please.": "0619",
        "Another glass of water, please.": "0620",
      },
    },
    "At the restaurant 4": {
      "selected": false,
      "lsWord": {
        "32 [thirty-two]": "0621",
        "At the restaurant 4": "0622",
        "I�d like chips / French fries (am.) with ketchup.": "0623",
        "And two with mayonnaise.": "0624",
        "And three sausages with mustard.": "0625",
        "What vegetables do you have?": "0626",
        "Do you have beans?": "0627",
        "Do you have cauliflower?": "0628",
        "I like to eat (sweet) corn.": "0629",
        "I like to eat cucumber.": "0630",
        "I like to eat tomatoes.": "0631",
        "Do you also like to eat leek?": "0632",
        "Do you also like to eat sauerkraut?": "0633",
        "Do you also like to eat lentils?": "0634",
        "Do you also like to eat carrots?": "0635",
        "Do you also like to eat broccoli?": "0636",
        "Do you also like to eat peppers?": "0637",
        "I don�t like onions.": "0638",
        "I don�t like olives.": "0639",
        "I don�t like mushrooms.": "0640",
      },
    },
    "At the train station": {
      "selected": false,
      "lsWord": {
        "33 [thirty-three]": "0641",
        "At the train station": "0642",
        "When is the next train to Berlin?": "0643",
        "When is the next train to Paris?": "0644",
        "When is the next train to London?": "0645",
        "When does the train for Warsaw leave?": "0646",
        "When does the train for Stockholm leave?": "0647",
        "When does the train for Budapest leave?": "0648",
        "I�d like a ticket to Madrid.": "0649",
        "I�d like a ticket to Prague.": "0650",
        "I�d like a ticket to Bern.": "0651",
        "When does the train arrive in Vienna?": "0652",
        "When does the train arrive in Moscow?": "0653",
        "When does the train arrive in Amsterdam?": "0654",
        "Do I have to change trains?": "0655",
        "From which platform does the train leave?": "0656",
        "Does the train have sleepers?": "0657",
        "I�d like a one-way ticket to Brussels.": "0658",
        "I�d like a return ticket to Copenhagen.": "0659",
        "What does a berth in the sleeper cost?": "0660",
      },
    },
    "On the train": {
      "selected": false,
      "lsWord": {
        "34 [thirty-four]": "0661",
        "On the train": "0662",
        "Is that the train to Berlin?": "0663",
        "When does the train leave?": "0664",
        "When does the train arrive in Berlin?": "0665",
        "Excuse me, may I pass?": "0666",
        "I think this is my seat.": "0667",
        "I think you�re sitting in my seat.": "0668",
        "Where is the sleeper?": "0669",
        "The sleeper is at the end of the train.": "0670",
        "And where is the dining car? � At the front.": "0671",
        "Can I sleep below?": "0672",
        "Can I sleep in the middle?": "0673",
        "Can I sleep at the top?": "0674",
        "When will we get to the border?": "0675",
        "How long does the journey to Berlin take?": "0676",
        "Is the train delayed?": "0677",
        "Do you have something to read?": "0678",
        "Can one get something to eat and to drink here?": "0679",
        "Could you please wake me up at 7 o�clock?": "0680",
      },
    },
    "At the airport": {
      "selected": false,
      "lsWord": {
        "35 [thirty-five]": "0681",
        "At the airport": "0682",
        "I�d like to book a flight to Athens.": "0683",
        "Is it a direct flight?": "0684",
        "A window seat, non-smoking, please.": "0685",
        "I would like to confirm my reservation.": "0686",
        "I would like to cancel my reservation.": "0687",
        "I would like to change my reservation.": "0688",
        "When is the next flight to Rome?": "0689",
        "Are there two seats available?": "0690",
        "No, we have only one seat available.": "0691",
        "When do we land?": "0692",
        "When will we be there?": "0693",
        "When does a bus go to the city centre / center (am.)?": "0694",
        "Is that your suitcase?": "0695",
        "Is that your bag?": "0696",
        "Is that your luggage?": "0697",
        "How much luggage can I take?": "0698",
        "Twenty kilos.": "0699",
        "What? Only twenty kilos?": "0700",
      },
    },
    "Public transportation": {
      "selected": false,
      "lsWord": {
        "36 [thirty-six]": "0701",
        "Public transportation": "0702",
        "Where is the bus stop?": "0703",
        "Which bus goes to the city centre / center (am.)?": "0704",
        "Which bus do I have to take?": "0705",
        "Do I have to change?": "0706",
        "Where do I have to change?": "0707",
        "How much does a ticket cost?": "0708",
        "How many stops are there before downtown / the city centre?": "0709",
        "You have to get off here.": "0710",
        "You have to get off at the back.": "0711",
        "The next train is in 5 minutes.": "0712",
        "The next tram is in 10 minutes.": "0713",
        "The next bus is in 15 minutes.": "0714",
        "When is the last train?": "0715",
        "When is the last tram?": "0716",
        "When is the last bus?": "0717",
        "Do you have a ticket?": "0718",
        "A ticket? � No, I don�t have one.": "0719",
        "Then you have to pay a fine.": "0720",
      },
    },
    "En route": {
      "selected": false,
      "lsWord": {
        "37 [thirty-seven]": "0721",
        "En route": "0722",
        "He drives a motorbike.": "0723",
        "He rides a bicycle.": "0724",
        "He walks.": "0725",
        "He goes by ship.": "0726",
        "He goes by boat.": "0727",
        "He swims.": "0728",
        "Is it dangerous here?": "0729",
        "Is it dangerous to hitchhike alone?": "0730",
        "Is it dangerous to go for a walk at night?": "0731",
        "We got lost.": "0732",
        "We�re on the wrong road.": "0733",
        "We must turn around.": "0734",
        "Where can one park here?": "0735",
        "Is there a parking lot here?": "0736",
        "How long can one park here?": "0737",
        "Do you ski?": "0738",
        "Do you take the ski lift to the top?": "0739",
        "Can one rent skis here?": "0740",
      },
    },
    "In the taxi": {
      "selected": false,
      "lsWord": {
        "38 [thirty-eight]": "0741",
        "In the taxi": "0742",
        "Please call a taxi.": "0743",
        "What does it cost to go to the station?": "0744",
        "What does it cost to go to the airport?": "0745",
        "Please go straight ahead.": "0746",
        "Please turn right here.": "0747",
        "Please turn left at the corner.": "0748",
        "I�m in a hurry.": "0749",
        "I have time.": "0750",
        "Please drive slowly.": "0751",
        "Please stop here.": "0752",
        "Please wait a moment.": "0753",
        "I�ll be back immediately.": "0754",
        "Please give me a receipt.": "0755",
        "I have no change.": "0756",
        "That is okay, please keep the change.": "0757",
        "Drive me to this address.": "0758",
        "Drive me to my hotel.": "0759",
        "Drive me to the beach.": "0760",
      },
    },
    "Car breakdown": {
      "selected": false,
      "lsWord": {
        "39 [thirty-nine]": "0761",
        "Car breakdown": "0762",
        "Where is the next gas station?": "0763",
        "I have a flat tyre / tire (am.).": "0764",
        "Can you change the tyre / tire (am.)?": "0765",
        "I need a few litres / liters (am.) of diesel.": "0766",
        "I have no more petrol / gas (am.).": "0767",
        "Do you have a petrol can / jerry can / gas can (am.)?": "0768",
        "Where can I make a call?": "0769",
        "I need a towing service.": "0770",
        "I�m looking for a garage.": "0771",
        "An accident has occurred.": "0772",
        "Where is the nearest telephone?": "0773",
        "Do you have a mobile / cell phone (am.) with you?": "0774",
        "We need help.": "0775",
        "Call a doctor!": "0776",
        "Call the police!": "0777",
        "Your papers, please.": "0778",
        "Your licence / license (am.), please.": "0779",
        "Your registration, please.": "0780",
      },
    },
    "Asking for directions": {
      "selected": false,
      "lsWord": {
        "40 [forty]": "0781",
        "Asking for directions": "0782",
        "Excuse me!": "0783",
        "Can you help me?": "0784",
        "Is there a good restaurant around here?": "0785",
        "Take a left at the corner.": "0786",
        "Then go straight for a while.": "0787",
        "Then go right for a hundred metres / meters (am.).": "0788",
        "You can also take the bus.": "0789",
        "You can also take the tram.": "0790",
        "You can also follow me with your car.": "0791",
        "How do I get to the football / soccer (am.) stadium?": "0792",
        "Cross the bridge!": "0793",
        "Go through the tunnel!": "0794",
        "Drive until you reach the third traffic light.": "0795",
        "Then turn into the first street on your right.": "0796",
        "Then drive straight through the next intersection.": "0797",
        "Excuse me, how do I get to the airport?": "0798",
        "It is best if you take the underground / subway (am.).": "0799",
        "Simply get out at the last stop.": "0800",
      },
    },
    "Where is ... ?": {
      "selected": false,
      "lsWord": {
        "41 [forty-one]": "0801",
        "Where is ... ?": "0802",
        "Where is the tourist information office?": "0803",
        "Do you have a city map for me?": "0804",
        "Can one reserve a room here?": "0805",
        "Where is the old city?": "0806",
        "Where is the cathedral?": "0807",
        "Where is the museum?": "0808",
        "Where can one buy stamps?": "0809",
        "Where can one buy flowers?": "0810",
        "Where can one buy tickets?": "0811",
        "Where is the harbour / harbor (am.)?": "0812",
        "Where is the market?": "0813",
        "Where is the castle?": "0814",
        "When does the tour begin?": "0815",
        "When does the tour end?": "0816",
        "How long is the tour?": "0817",
        "I would like a guide who speaks German.": "0818",
        "I would like a guide who speaks Italian.": "0819",
        "I would like a guide who speaks French.": "0820",
      },
    },
    "City tour": {
      "selected": false,
      "lsWord": {
        "42 [forty-two]": "0821",
        "City tour": "0822",
        "Is the market open on Sundays?": "0823",
        "Is the fair open on Mondays?": "0824",
        "Is the exhibition open on Tuesdays?": "0825",
        "Is the zoo open on Wednesdays?": "0826",
        "Is the museum open on Thursdays?": "0827",
        "Is the gallery open on Fridays?": "0828",
        "Can one take photographs?": "0829",
        "Does one have to pay an entrance fee?": "0830",
        "How much is the entrance fee?": "0831",
        "Is there a discount for groups?": "0832",
        "Is there a discount for children?": "0833",
        "Is there a discount for students?": "0834",
        "What building is that?": "0835",
        "How old is the building?": "0836",
        "Who built the building?": "0837",
        "I�m interested in architecture.": "0838",
        "I�m interested in art.": "0839",
        "I�m interested in paintings.": "0840",
      },
    },
    "At the zoo": {
      "selected": false,
      "lsWord": {
        "43 [forty-three]": "0841",
        "At the zoo": "0842",
        "The zoo is there.": "0843",
        "The giraffes are there.": "0844",
        "Where are the bears?": "0845",
        "Where are the elephants?": "0846",
        "Where are the snakes?": "0847",
        "Where are the lions?": "0848",
        "I have a camera.": "0849",
        "I also have a video camera.": "0850",
        "Where can I find a battery?": "0851",
        "Where are the penguins?": "0852",
        "Where are the kangaroos?": "0853",
        "Where are the rhinos?": "0854",
        "Where is the toilet / restroom (am.)?": "0855",
        "There is a caf� over there.": "0856",
        "There is a restaurant over there.": "0857",
        "Where are the camels?": "0858",
        "Where are the gorillas and the zebras?": "0859",
        "Where are the tigers and the crocodiles?": "0860",
      },
    },
    "Going out in the evening": {
      "selected": false,
      "lsWord": {
        "44 [forty-four]": "0861",
        "Going out in the evening": "0862",
        "Is there a disco here?": "0863",
        "Is there a nightclub here?": "0864",
        "Is there a pub here?": "0865",
        "What�s playing at the theatre / theater (am.) this evening?": "0866",
        "What�s playing at the cinema / movies (am.) this evening?": "0867",
        "What�s on TV this evening?": "0868",
        "Are tickets for the theatre / theater (am.) still available?": "0869",
        "Are tickets for the cinema / movies (am.) still available?": "0870",
        "Are tickets for the football / soccer am. game still available?": "0871",
        "I want to sit in the back.": "0872",
        "I want to sit somewhere in the middle.": "0873",
        "I want to sit at the front.": "0874",
        "Could you recommend something?": "0875",
        "When does the show begin?": "0876",
        "Can you get me a ticket?": "0877",
        "Is there a golf course nearby?": "0878",
        "Is there a tennis court nearby?": "0879",
        "Is there an indoor swimming pool nearby?": "0880",
      },
    },
    "At the cinema": {
      "selected": false,
      "lsWord": {
        "45 [forty-five]": "0881",
        "At the cinema": "0882",
        "We want to go to the cinema.": "0883",
        "A good film is playing today.": "0884",
        "The film is brand new.": "0885",
        "Where is the cash register?": "0886",
        "Are seats still available?": "0887",
        "How much are the admission tickets?": "0888",
        "When does the show begin?": "0889",
        "How long is the film?": "0890",
        "Can one reserve tickets?": "0891",
        "I want to sit at the back.": "0892",
        "I want to sit at the front.": "0893",
        "I want to sit in the middle.": "0894",
        "The film was exciting.": "0895",
        "The film was not boring.": "0896",
        "But the book on which the film was based was better.": "0897",
        "How was the music?": "0898",
        "How were the actors?": "0899",
        "Were there English subtitles?": "0900",
      },
    },
    "In the discotheque": {
      "selected": false,
      "lsWord": {
        "46 [forty-six]": "0901",
        "In the discotheque": "0902",
        "Is this seat taken?": "0903",
        "May I sit with you?": "0904",
        "Sure.": "0905",
        "How do you like the music?": "0906",
        "A little too loud.": "0907",
        "But the band plays very well.": "0908",
        "Do you come here often?": "0909",
        "No, this is the first time.": "0910",
        "I�ve never been here before.": "0911",
        "Would you like to dance?": "0912",
        "Maybe later.": "0913",
        "I can�t dance very well.": "0914",
        "It�s very easy.": "0915",
        "I�ll show you.": "0916",
        "No, maybe some other time.": "0917",
        "Are you waiting for someone?": "0918",
        "Yes, for my boyfriend.": "0919",
        "There he is!": "0920",
      },
    },
    "Preparing a trip": {
      "selected": false,
      "lsWord": {
        "47 [forty-seven]": "0921",
        "Preparing a trip": "0922",
        "You have to pack our suitcase!": "0923",
        "Don�t forget anything!": "0924",
        "You need a big suitcase!": "0925",
        "Don�t forget your passport!": "0926",
        "Don�t forget your ticket!": "0927",
        "Don�t forget your traveller�s cheques / traveler�s checks (am.)!": "0928",
        "Take some suntan lotion with you.": "0929",
        "Take the sun-glasses with you.": "0930",
        "Take the sun hat with you.": "0931",
        "Do you want to take a road map?": "0932",
        "Do you want to take a travel guide?": "0933",
        "Do you want to take an umbrella?": "0934",
        "Remember to take pants, shirts and socks.": "0935",
        "Remember to take ties, belts and sports jackets.": "0936",
        "Remember to take pyjamas, nightgowns and t-shirts.": "0937",
        "You need shoes, sandals and boots.": "0938",
        "You need handkerchiefs, soap and a nail clipper.": "0939",
        "You need a comb, a toothbrush and toothpaste.": "0940",
      },
    },
    "Vacation activities": {
      "selected": false,
      "lsWord": {
        "48 [forty-eight]": "0941",
        "Vacation activities": "0942",
        "Is the beach clean?": "0943",
        "Can one swim there?": "0944",
        "Isn�t it dangerous to swim there?": "0945",
        "Can one rent a sun umbrella / parasol here?": "0946",
        "Can one rent a deck chair here?": "0947",
        "Can one rent a boat here?": "0948",
        "I would like to surf.": "0949",
        "I would like to dive.": "0950",
        "I would like to water ski.": "0951",
        "Can one rent a surfboard?": "0952",
        "Can one rent diving equipment?": "0953",
        "Can one rent water skis?": "0954",
        "I�m only a beginner.": "0955",
        "I�m moderately good.": "0956",
        "I�m pretty good at it.": "0957",
        "Where is the ski lift?": "0958",
        "Do you have skis?": "0959",
        "Do you have ski boots?": "0960",
      },
    },
    "Sports": {
      "selected": false,
      "lsWord": {
        "49 [forty-nine]": "0961",
        "Sports": "0962",
        "Do you exercise?": "0963",
        "Yes, I need some exercise.": "0964",
        "I am a member of a sports club.": "0965",
        "We play football / soccer (am.).": "0966",
        "We swim sometimes.": "0967",
        "Or we cycle.": "0968",
        "There is a football / soccer (am.) stadium in our city.": "0969",
        "There is also a swimming pool with a sauna.": "0970",
        "And there is a golf course.": "0971",
        "What is on TV?": "0972",
        "There is a football / soccer (am.) match on now.": "0973",
        "The German team is playing against the English one.": "0974",
        "Who is winning?": "0975",
        "I have no idea.": "0976",
        "It is currently a tie.": "0977",
        "The referee is from Belgium.": "0978",
        "Now there is a penalty.": "0979",
        "Goal! One � zero!": "0980",
      },
    },
    "In the swimming pool": {
      "selected": false,
      "lsWord": {
        "50 [fifty]": "0981",
        "In the swimming pool": "0982",
        "It is hot today.": "0983",
        "Shall we go to the swimming pool?": "0984",
        "Do you feel like swimming?": "0985",
        "Do you have a towel?": "0986",
        "Do you have swimming trunks?": "0987",
        "Do you have a bathing suit?": "0988",
        "Can you swim?": "0989",
        "Can you dive?": "0990",
        "Can you jump in the water?": "0991",
        "Where is the shower?": "0992",
        "Where is the changing room?": "0993",
        "Where are the swimming goggles?": "0994",
        "Is the water deep?": "0995",
        "Is the water clean?": "0996",
        "Is the water warm?": "0997",
        "I am freezing.": "0998",
        "The water is too cold.": "0999",
        "I am getting out of the water now.": "1000",
      },
    },
    "Running errands": {
      "selected": false,
      "lsWord": {
        "51 [fifty-one]": "1001",
        "Running errands": "1002",
        "I want to go to the library.": "1003",
        "I want to go to the bookstore.": "1004",
        "I want to go to the newspaper stand.": "1005",
        "I want to borrow a book.": "1006",
        "I want to buy a book.": "1007",
        "I want to buy a newspaper.": "1008",
        "I want to go to the library to borrow a book.": "1009",
        "I want to go to the bookstore to buy a book.": "1010",
        "I want to go to the kiosk / newspaper stand to buy a newspaper.": "1011",
        "I want to go to the optician.": "1012",
        "I want to go to the supermarket.": "1013",
        "I want to go to the bakery.": "1014",
        "I want to buy some glasses.": "1015",
        "I want to buy fruit and vegetables.": "1016",
        "I want to buy rolls and bread.": "1017",
        "I want to go to the optician to buy glasses.": "1018",
        "I want to go to the supermarket to buy fruit and vegetables.": "1019",
        "I want to go to the baker to buy rolls and bread.": "1020",
      },
    },
    "In the department store": {
      "selected": false,
      "lsWord": {
        "52 [fifty-two]": "1021",
        "In the department store": "1022",
        "Shall we go to the department store?": "1023",
        "I have to go shopping.": "1024",
        "I want to do a lot of shopping.": "1025",
        "Where are the office supplies?": "1026",
        "I need envelopes and stationery.": "1027",
        "I need pens and markers.": "1028",
        "Where is the furniture?": "1029",
        "I need a cupboard and a chest of drawers.": "1030",
        "I need a desk and a bookshelf.": "1031",
        "Where are the toys?": "1032",
        "I need a doll and a teddy bear.": "1033",
        "I need a football and a chess board.": "1034",
        "Where are the tools?": "1035",
        "I need a hammer and a pair of pliers.": "1036",
        "I need a drill and a screwdriver.": "1037",
        "Where is the jewellery / jewelry (am.) department?": "1038",
        "I need a chain and a bracelet.": "1039",
        "I need a ring and earrings.": "1040",
      },
    },
    "Shops": {
      "selected": false,
      "lsWord": {
        "53 [fifty-three]": "1041",
        "Shops": "1042",
        "We�re looking for a sports shop.": "1043",
        "We�re looking for a butcher shop.": "1044",
        "We�re looking for a pharmacy / drugstore (am.).": "1045",
        "We want to buy a football.": "1046",
        "We want to buy salami.": "1047",
        "We want to buy medicine.": "1048",
        "We�re looking for a sports shop to buy a football.": "1049",
        "We�re looking for a butcher shop to buy salami.": "1050",
        "We�re looking for a drugstore to buy medicine.": "1051",
        "I�m looking for a jeweller / jeweler (am.).": "1052",
        "I�m looking for a photo equipment store.": "1053",
        "I�m looking for a confectionery.": "1054",
        "I actually plan to buy a ring.": "1055",
        "I actually plan to buy a roll of film.": "1056",
        "I actually plan to buy a cake.": "1057",
        "I�m looking for a jeweler to buy a ring.": "1058",
        "I�m looking for a photo shop to buy a roll of film.": "1059",
        "I�m looking for a confectionery to buy a cake.": "1060",
      },
    },
    "Shopping": {
      "selected": false,
      "lsWord": {
        "54 [fifty-four]": "1061",
        "Shopping": "1062",
        "I want to buy a present.": "1063",
        "But nothing too expensive.": "1064",
        "Maybe a handbag?": "1065",
        "Which color would you like?": "1066",
        "Black, brown or white?": "1067",
        "A large one or a small one?": "1068",
        "May I see this one, please?": "1069",
        "Is it made of leather?": "1070",
        "Or is it made of plastic?": "1071",
        "Of leather, of course.": "1072",
        "This is very good quality.": "1073",
        "And the bag is really very reasonable.": "1074",
        "I like it.": "1075",
        "I�ll take it.": "1076",
        "Can I exchange it if needed?": "1077",
        "Of course.": "1078",
        "We�ll gift wrap it.": "1079",
        "The cashier is over there.": "1080",
      },
    },
    "Working": {
      "selected": false,
      "lsWord": {
        "55 [fifty-five]": "1081",
        "Working": "1082",
        "What do you do for a living?": "1083",
        "My husband is a doctor.": "1084",
        "I work as a nurse part-time.": "1085",
        "We will soon receive our pension.": "1086",
        "But taxes are high.": "1087",
        "And health insurance is expensive.": "1088",
        "What would you like to become some day?": "1089",
        "I would like to become an engineer.": "1090",
        "I want to go to college.": "1091",
        "I am an intern.": "1092",
        "I do not earn much.": "1093",
        "I am doing an internship abroad.": "1094",
        "That is my boss.": "1095",
        "I have nice colleagues.": "1096",
        "We always go to the cafeteria at noon.": "1097",
        "I am looking for a job.": "1098",
        "I have already been unemployed for a year.": "1099",
        "There are too many unemployed people in this country.": "1100",
      },
    },
    "Feelings": {
      "selected": false,
      "lsWord": {
        "56 [fifty-six]": "1101",
        "Feelings": "1102",
        "to feel like / want to": "1103",
        "We feel like. / We want to.": "1104",
        "We don�t feel like. / We do�t want to.": "1105",
        "to be afraid": "1106",
        "I�m afraid.": "1107",
        "I am not afraid.": "1108",
        "to have time": "1109",
        "He has time.": "1110",
        "He has no time.": "1111",
        "to be bored": "1112",
        "She is bored.": "1113",
        "She is not bored.": "1114",
        "to be hungry": "1115",
        "Are you hungry?": "1116",
        "Aren�t you hungry?": "1117",
        "to be thirsty": "1118",
        "They are thirsty.": "1119",
        "They are not thirsty.": "1120",
      },
    },
    "At the doctor": {
      "selected": false,
      "lsWord": {
        "57 [fifty-seven]": "1121",
        "At the doctor": "1122",
        "I have a doctor�s appointment.": "1123",
        "I have the appointment at ten o�clock.": "1124",
        "What is your name?": "1125",
        "Please take a seat in the waiting room.": "1126",
        "The doctor is on his way.": "1127",
        "What insurance company do you belong to?": "1128",
        "What can I do for you?": "1129",
        "Do you have any pain?": "1130",
        "Where does it hurt?": "1131",
        "I always have back pain.": "1132",
        "I often have headaches.": "1133",
        "I sometimes have stomach aches.": "1134",
        "Remove your top!": "1135",
        "Lie down on the examining table.": "1136",
        "Your blood pressure is okay.": "1137",
        "I will give you an injection.": "1138",
        "I will give you some pills.": "1139",
        "I am giving you a prescription for the pharmacy.": "1140",
      },
    },
    "Parts of the body": {
      "selected": false,
      "lsWord": {
        "58 [fifty-eight]": "1141",
        "Parts of the body": "1142",
        "I am drawing a man.": "1143",
        "First the head.": "1144",
        "The man is wearing a hat.": "1145",
        "One cannot see the hair.": "1146",
        "One cannot see the ears either.": "1147",
        "One cannot see his back either.": "1148",
        "I am drawing the eyes and the mouth.": "1149",
        "The man is dancing and laughing.": "1150",
        "The man has a long nose.": "1151",
        "He is carrying a cane in his hands.": "1152",
        "He is also wearing a scarf around his neck.": "1153",
        "It is winter and it is cold.": "1154",
        "The arms are athletic.": "1155",
        "The legs are also athletic.": "1156",
        "The man is made of snow.": "1157",
        "He is neither wearing pants nor a coat.": "1158",
        "But the man is not freezing.": "1159",
        "He is a snowman.": "1160",
      },
    },
    "At the post office": {
      "selected": false,
      "lsWord": {
        "59 [fifty-nine]": "1161",
        "At the post office": "1162",
        "Where is the nearest post office?": "1163",
        "Is the post office far from here?": "1164",
        "Where is the nearest mail box?": "1165",
        "I need a couple of stamps.": "1166",
        "For a card and a letter.": "1167",
        "How much is the postage to America?": "1168",
        "How heavy is the package?": "1169",
        "Can I send it by air mail?": "1170",
        "How long will it take to get there?": "1171",
        "Where can I make a call?": "1172",
        "Where is the nearest telephone booth?": "1173",
        "Do you have calling cards?": "1174",
        "Do you have a telephone directory?": "1175",
        "Do you know the area code for Austria?": "1176",
        "One moment, I�ll look it up.": "1177",
        "The line is always busy.": "1178",
        "Which number did you dial?": "1179",
        "You have to dial a zero first!": "1180",
      },
    },
    "At the bank": {
      "selected": false,
      "lsWord": {
        "60 [sixty]": "1181",
        "At the bank": "1182",
        "I would like to open an account.": "1183",
        "Here is my passport.": "1184",
        "And here is my address.": "1185",
        "I want to deposit money in my account.": "1186",
        "I want to withdraw money from my account.": "1187",
        "I want to pick up the bank statements.": "1188",
        "I want to cash a traveller�s cheque / traveler�s check (am.).": "1189",
        "What are the fees?": "1190",
        "Where should I sign?": "1191",
        "I�m expecting a transfer from Germany.": "1192",
        "Here is my account number.": "1193",
        "Has the money arrived?": "1194",
        "I want to change money.": "1195",
        "I need US-Dollars.": "1196",
        "Could you please give me small notes / bills (am.)?": "1197",
        "Is there a cashpoint / an ATM (am.)?": "1198",
        "How much money can one withdraw?": "1199",
        "Which credit cards can one use?": "1200",
      },
    },
    "Ordinal numbers": {
      "selected": false,
      "lsWord": {
        "61 [sixty-one]": "1201",
        "Ordinal numbers": "1202",
        "The first month is January.": "1203",
        "The second month is February.": "1204",
        "The third month is March.": "1205",
        "The fourth month is April.": "1206",
        "The fifth month is May.": "1207",
        "The sixth month is June.": "1208",
        "Six months make half a year.": "1209",
        "January, February, March,": "1210",
        "April, May and June.": "1211",
        "The seventh month is July.": "1212",
        "The eighth month is August.": "1213",
        "The ninth month is September.": "1214",
        "The tenth month is October.": "1215",
        "The eleventh month is November.": "1216",
        "The twelfth month is December.": "1217",
        "Twelve months make a year.": "1218",
        "July, August, September,": "1219",
        "October, November and December.": "1220",
      },
    },
    "Asking questions 1": {
      "selected": false,
      "lsWord": {
        "62 [sixty-two]": "1221",
        "Asking questions 1": "1222",
        "to learn": "1223",
        "Do the students learn a lot?": "1224",
        "No, they learn a little.": "1225",
        "to ask": "1226",
        "Do you often ask the teacher questions?": "1227",
        "No, I don�t ask him questions often.": "1228",
        "to reply": "1229",
        "Please reply.": "1230",
        "I reply.": "1231",
        "to work": "1232",
        "Is he working right now?": "1233",
        "Yes, he is working right now.": "1234",
        "to come": "1235",
        "Are you coming?": "1236",
        "Yes, we are coming soon.": "1237",
        "to live": "1238",
        "Do you live in Berlin?": "1239",
        "Yes, I live in Berlin.": "1240",
      },
    },
    "Asking questions 2": {
      "selected": false,
      "lsWord": {
        "63 [sixty-three]": "1241",
        "Asking questions 2": "1242",
        "I have a hobby.": "1243",
        "I play tennis.": "1244",
        "Where is the tennis court?": "1245",
        "Do you have a hobby?": "1246",
        "I play football / soccer (am.).": "1247",
        "Where is the football / soccer (am.) field?": "1248",
        "My arm hurts.": "1249",
        "My foot and hand also hurt.": "1250",
        "Is there a doctor?": "1251",
        "I have a car / an automobile.": "1252",
        "I also have a motorcycle.": "1253",
        "Where could I park?": "1254",
        "I have a sweater.": "1255",
        "I also have a jacket and a pair of jeans.": "1256",
        "Where is the washing machine?": "1257",
        "I have a plate.": "1258",
        "I have a knife, a fork and a spoon.": "1259",
        "Where is the salt and pepper?": "1260",
      },
    },
    "Negation 1": {
      "selected": false,
      "lsWord": {
        "64 [sixty-four]": "1261",
        "Negation 1": "1262",
        "I don�t understand the word.": "1263",
        "I don�t understand the sentence.": "1264",
        "I don�t understand the meaning.": "1265",
        "the teacher": "1266",
        "Do you understand the teacher?": "1267",
        "Yes, I understand him well.": "1268",
        "Yes, I understand her well.": "1271",
        "the people": "1272",
        "Do you understand the people?": "1273",
        "No, I don�t understand them so well.": "1274",
        "the girlfriend": "1275",
        "Do you have a girlfriend?": "1276",
        "Yes, I do.": "1277",
        "the daughter": "1278",
        "Do you have a daughter?": "1279",
        "No, I don�t.": "1280",
      },
    },
    "Negation 2": {
      "selected": false,
      "lsWord": {
        "65 [sixty-five]": "1281",
        "Negation 2": "1282",
        "Is the ring expensive?": "1283",
        "No, it costs only one hundred Euros.": "1284",
        "But I have only fifty.": "1285",
        "Are you finished?": "1286",
        "No, not yet.": "1287",
        "But I�ll be finished soon.": "1288",
        "Do you want some more soup?": "1289",
        "No, I don�t want anymore.": "1290",
        "But another ice cream.": "1291",
        "Have you lived here long?": "1292",
        "No, only for a month.": "1293",
        "But I already know a lot of people.": "1294",
        "Are you driving home tomorrow?": "1295",
        "No, only on the weekend.": "1296",
        "But I will be back on Sunday.": "1297",
        "Is your daughter an adult?": "1298",
        "No, she is only seventeen.": "1299",
        "But she already has a boyfriend.": "1300",
      },
    },
    "Possessive pronouns 1": {
      "selected": false,
      "lsWord": {
        "66 [sixty-six]": "1301",
        "Possessive pronouns 1": "1302",
        "I � my": "1303",
        "I can�t find my key.": "1304",
        "I can�t find my ticket.": "1305",
        "you � your": "1306",
        "Have you found your key?": "1307",
        "Have you found your ticket?": "1308",
        "he � his": "1309",
        "Do you know where his key is?": "1310",
        "Do you know where his ticket is?": "1311",
        "she � her": "1312",
        "Her money is gone.": "1313",
        "And her credit card is also gone.": "1314",
        "we � our": "1315",
        "Our grandfather is ill.": "1316",
        "Our grandmother is healthy.": "1317",
        "Children, where is your father?": "1319",
        "Children, where is your mother?": "1320",
      },
    },
    "Possessive pronouns 2": {
      "selected": false,
      "lsWord": {
        "67 [sixty-seven]": "1321",
        "Possessive pronouns 2": "1322",
        "the glasses": "1323",
        "He has forgotten his glasses.": "1324",
        "Where has he left his glasses?": "1325",
        "the clock": "1326",
        "His clock isn�t working.": "1327",
        "The clock hangs on the wall.": "1328",
        "the passport": "1329",
        "He has lost his passport.": "1330",
        "Where is his passport then?": "1331",
        "they � their": "1332",
        "The children cannot find their parents.": "1333",
        "Here come their parents!": "1334",
        "you � your": "1335",
        "How was your trip, Mr. Miller?": "1336",
        "Where is your wife, Mr. Miller?": "1337",
        "How was your trip, Mrs. Smith?": "1339",
        "Where is your husband, Mrs. Smith?": "1340",
      },
    },
    "big � small": {
      "selected": false,
      "lsWord": {
        "68 [sixty-eight]": "1341",
        "big � small": "1342",
        "big and small": "1343",
        "The elephant is big.": "1344",
        "The mouse is small.": "1345",
        "dark and bright": "1346",
        "The night is dark.": "1347",
        "The day is bright.": "1348",
        "old and young": "1349",
        "Our grandfather is very old.": "1350",
        "70 years ago he was still young.": "1351",
        "beautiful and ugly": "1352",
        "The butterfly is beautiful.": "1353",
        "The spider is ugly.": "1354",
        "fat and thin": "1355",
        "A woman who weighs a hundred kilos is fat.": "1356",
        "A man who weighs fifty kilos is thin.": "1357",
        "expensive and cheap": "1358",
        "The car is expensive.": "1359",
        "The newspaper is cheap.": "1360",
      },
    },
    "to need � to want to": {
      "selected": false,
      "lsWord": {
        "69 [sixty-nine]": "1361",
        "to need � to want to": "1362",
        "I need a bed.": "1363",
        "I want to sleep.": "1364",
        "Is there a bed here?": "1365",
        "I need a lamp.": "1366",
        "I want to read.": "1367",
        "Is there a lamp here?": "1368",
        "I need a telephone.": "1369",
        "I want to make a call.": "1370",
        "Is there a telephone here?": "1371",
        "I need a camera.": "1372",
        "I want to take photographs.": "1373",
        "Is there a camera here?": "1374",
        "I need a computer.": "1375",
        "I want to send an email.": "1376",
        "Is there a computer here?": "1377",
        "I need a pen.": "1378",
        "I want to write something.": "1379",
        "Is there a sheet of paper and a pen here?": "1380",
      },
    },
    "to like something": {
      "selected": false,
      "lsWord": {
        "70 [seventy]": "1381",
        "to like something": "1382",
        "Would you like to smoke?": "1383",
        "Would you like to dance?": "1384",
        "Would you like to go for a walk?": "1385",
        "I would like to smoke.": "1386",
        "Would you like a cigarette?": "1387",
        "He wants a light.": "1388",
        "I want to drink something.": "1389",
        "I want to eat something.": "1390",
        "I want to relax a little.": "1391",
        "I want to ask you something.": "1392",
        "I want to ask you for something.": "1393",
        "I want to treat you to something.": "1394",
        "What would you like?": "1395",
        "Would you like a coffee?": "1396",
        "Or do you prefer a tea?": "1397",
        "We want to drive home.": "1398",
        "Do you want a taxi?": "1399",
        "They want to make a call.": "1400",
      },
    },
    "to want something": {
      "selected": false,
      "lsWord": {
        "71 [seventy-one]": "1401",
        "to want something": "1402",
        "What do you want to do?": "1403",
        "Do you want to play football / soccer (am.)?": "1404",
        "Do you want to visit friends?": "1405",
        "to want": "1406",
        "I don�t want to arrive late.": "1407",
        "I don�t want to go there.": "1408",
        "I want to go home.": "1409",
        "I want to stay at home.": "1410",
        "I want to be alone.": "1411",
        "Do you want to stay here?": "1412",
        "Do you want to eat here?": "1413",
        "Do you want to sleep here?": "1414",
        "Do you want to leave tomorrow?": "1415",
        "Do you want to stay till tomorrow?": "1416",
        "Do you want to pay the bill only tomorrow?": "1417",
        "Do you want to go to the disco?": "1418",
        "Do you want to go to the cinema?": "1419",
        "Do you want to go to a caf�?": "1420",
      },
    },
    "to have to do something / must": {
      "selected": false,
      "lsWord": {
        "72 [seventy-two]": "1421",
        "to have to do something / must": "1422",
        "must": "1423",
        "I must post the letter.": "1424",
        "I must pay the hotel.": "1425",
        "You must get up early.": "1426",
        "You must work a lot.": "1427",
        "You must be punctual.": "1428",
        "He must fuel / get petrol / get gas (am.).": "1429",
        "He must repair the car.": "1430",
        "He must wash the car.": "1431",
        "She must shop.": "1432",
        "She must clean the apartment.": "1433",
        "She must wash the clothes.": "1434",
        "We must go to school at once.": "1435",
        "We must go to work at once.": "1436",
        "We must go to the doctor at once.": "1437",
        "You must wait for the bus.": "1438",
        "You must wait for the train.": "1439",
        "You must wait for the taxi.": "1440",
      },
    },
    "to be allowed to": {
      "selected": false,
      "lsWord": {
        "73 [seventy-three]": "1441",
        "to be allowed to": "1442",
        "Are you already allowed to drive?": "1443",
        "Are you already allowed to drink alcohol?": "1444",
        "Are you already allowed to travel abroad alone?": "1445",
        "may / to be allowed": "1446",
        "May we smoke here?": "1447",
        "Is smoking allowed here?": "1448",
        "May one pay by credit card?": "1449",
        "May one pay by cheque / check (am.)?": "1450",
        "May one only pay in cash?": "1451",
        "May I just make a call?": "1452",
        "May I just ask something?": "1453",
        "May I just say something?": "1454",
        "He is not allowed to sleep in the park.": "1455",
        "He is not allowed to sleep in the car.": "1456",
        "He is not allowed to sleep at the train station.": "1457",
        "May we take a seat?": "1458",
        "May we have the menu?": "1459",
        "May we pay separately?": "1460",
      },
    },
    "asking for something": {
      "selected": false,
      "lsWord": {
        "74 [seventy-four]": "1461",
        "asking for something": "1462",
        "Can you cut my hair?": "1463",
        "Not too short, please.": "1464",
        "A bit shorter, please.": "1465",
        "Can you develop the pictures?": "1466",
        "The pictures are on the CD.": "1467",
        "The pictures are in the camera.": "1468",
        "Can you fix the clock?": "1469",
        "The glass is broken.": "1470",
        "The battery is dead / empty.": "1471",
        "Can you iron the shirt?": "1472",
        "Can you clean the pants / trousers?": "1473",
        "Can you fix the shoes?": "1474",
        "Do you have a light?": "1475",
        "Do you have a match or a lighter?": "1476",
        "Do you have an ashtray?": "1477",
        "Do you smoke cigars?": "1478",
        "Do you smoke cigarettes?": "1479",
        "Do you smoke a pipe?": "1480",
      },
    },
    "giving reasons 1": {
      "selected": false,
      "lsWord": {
        "75 [seventy-five]": "1481",
        "giving reasons 1": "1482",
        "Why aren�t you coming?": "1483",
        "The weather is so bad.": "1484",
        "I am not coming because the weather is so bad.": "1485",
        "Why isn�t he coming?": "1486",
        "He isn�t invited.": "1487",
        "He isn�t coming because he isn�t invited.": "1488",
        "I have no time.": "1490",
        "I am not coming because I have no time.": "1491",
        "Why don�t you stay?": "1492",
        "I still have to work.": "1493",
        "I am not staying because I still have to work.": "1494",
        "Why are you going already?": "1495",
        "I am tired.": "1496",
        "I�m going because I�m tired.": "1497",
        "It is already late.": "1499",
        "I�m going because it is already late.": "1500",
      },
    },
    "giving reasons 2": {
      "selected": false,
      "lsWord": {
        "76 [seventy-six]": "1501",
        "giving reasons 2": "1502",
        "Why didn�t you come?": "1503",
        "I was ill.": "1504",
        "I didn�t come because I was ill.": "1505",
        "Why didn�t she come?": "1506",
        "She was tired.": "1507",
        "She didn�t come because she was tired.": "1508",
        "Why didn�t he come?": "1509",
        "He wasn�t interested.": "1510",
        "He didn�t come because he wasn�t interested.": "1511",
        "Our car is damaged.": "1513",
        "We didn�t come because our car is damaged.": "1514",
        "Why didn�t the people come?": "1515",
        "They missed the train.": "1516",
        "They didn�t come because they missed the train.": "1517",
        "I was not allowed to.": "1519",
        "I didn�t come because I was not allowed to.": "1520",
      },
    },
    "giving reasons 3": {
      "selected": false,
      "lsWord": {
        "77 [seventy-seven]": "1521",
        "giving reasons 3": "1522",
        "Why aren�t you eating the cake?": "1523",
        "I must lose weight.": "1524",
        "I�m not eating it because I must lose weight.": "1525",
        "Why aren�t you drinking the beer?": "1526",
        "I have to drive.": "1527",
        "I�m not drinking it because I have to drive.": "1528",
        "Why aren�t you drinking the coffee?": "1529",
        "It is cold.": "1530",
        "I�m not drinking it because it is cold.": "1531",
        "Why aren�t you drinking the tea?": "1532",
        "I have no sugar.": "1533",
        "I�m not drinking it because I don�t have any sugar.": "1534",
        "Why aren�t you eating the soup?": "1535",
        "I didn�t order it.": "1536",
        "I�m not eating it because I didn�t order it.": "1537",
        "Why don�t you eat the meat?": "1538",
        "I am a vegetarian.": "1539",
        "I�m not eating it because I am a vegetarian.": "1540",
      },
    },
    "Adjectives 1": {
      "selected": false,
      "lsWord": {
        "78 [seventy-eight]": "1541",
        "Adjectives 1": "1542",
        "an old lady": "1543",
        "a fat lady": "1544",
        "a curious lady": "1545",
        "a new car": "1546",
        "a fast car": "1547",
        "a comfortable car": "1548",
        "a blue dress": "1549",
        "a red dress": "1550",
        "a green dress": "1551",
        "a black bag": "1552",
        "a brown bag": "1553",
        "a white bag": "1554",
        "nice people": "1555",
        "polite people": "1556",
        "interesting people": "1557",
        "loving children": "1558",
        "cheeky children": "1559",
        "well behaved children": "1560",
      },
    },
    "Adjectives 2": {
      "selected": false,
      "lsWord": {
        "79 [seventy-nine]": "1561",
        "Adjectives 2": "1562",
        "I am wearing a blue dress.": "1563",
        "I am wearing a red dress.": "1564",
        "I am wearing a green dress.": "1565",
        "I�m buying a black bag.": "1566",
        "I�m buying a brown bag.": "1567",
        "I�m buying a white bag.": "1568",
        "I need a new car.": "1569",
        "I need a fast car.": "1570",
        "I need a comfortable car.": "1571",
        "An old lady lives at the top.": "1572",
        "A fat lady lives at the top.": "1573",
        "A curious lady lives below.": "1574",
        "Our guests were nice people.": "1575",
        "Our guests were polite people.": "1576",
        "Our guests were interesting people.": "1577",
        "I have lovely children.": "1578",
        "But the neighbours have naughty children.": "1579",
        "Are your children well behaved?": "1580",
      },
    },
    "Adjectives 3": {
      "selected": false,
      "lsWord": {
        "80 [eighty]": "1581",
        "Adjectives 3": "1582",
        "She has a dog.": "1583",
        "The dog is big.": "1584",
        "She has a big dog.": "1585",
        "She has a house.": "1586",
        "The house is small.": "1587",
        "She has a small house.": "1588",
        "He is staying in a hotel.": "1589",
        "The hotel is cheap.": "1590",
        "He is staying in a cheap hotel.": "1591",
        "He has a car.": "1592",
        "The car is expensive.": "1593",
        "He has an expensive car.": "1594",
        "He reads a novel.": "1595",
        "The novel is boring.": "1596",
        "He is reading a boring novel.": "1597",
        "She is watching a movie.": "1598",
        "The movie is exciting.": "1599",
        "She is watching an exciting movie.": "1600",
      },
    },
    "Past tense 1": {
      "selected": false,
      "lsWord": {
        "81 [eighty-one]": "1601",
        "Past tense 1": "1602",
        "to write": "1603",
        "He wrote a letter.": "1604",
        "And she wrote a card.": "1605",
        "to read": "1606",
        "He read a magazine.": "1607",
        "And she read a book.": "1608",
        "to take": "1609",
        "He took a cigarette.": "1610",
        "She took a piece of chocolate.": "1611",
        "He was disloyal, but she was loyal.": "1612",
        "He was lazy, but she was hard-working.": "1613",
        "He was poor, but she was rich.": "1614",
        "He had no money, only debts.": "1615",
        "He had no luck, only bad luck.": "1616",
        "He had no success, only failure.": "1617",
        "He was not satisfied, but dissatisfied.": "1618",
        "He was not happy, but sad.": "1619",
        "He was not friendly, but unfriendly.": "1620",
      },
    },
    "Past tense 2": {
      "selected": false,
      "lsWord": {
        "82 [eighty-two]": "1621",
        "Past tense 2": "1622",
        "Did you have to call an ambulance?": "1623",
        "Did you have to call the doctor?": "1624",
        "Did you have to call the police?": "1625",
        "Do you have the telephone number? I had it just now.": "1626",
        "Do you have the address? I had it just now.": "1627",
        "Do you have the city map? I had it just now.": "1628",
        "Did he come on time? He could not come on time.": "1629",
        "Did he find the way? He could not find the way.": "1630",
        "Did he understand you? He could not understand me.": "1631",
        "Why could you not come on time?": "1632",
        "Why could you not find the way?": "1633",
        "Why could you not understand him?": "1634",
        "I could not come on time because there were no buses.": "1635",
        "I could not find the way because I had no city map.": "1636",
        "I could not understand him because the music was so loud.": "1637",
        "I had to take a taxi.": "1638",
        "I had to buy a city map.": "1639",
        "I had to switch off the radio.": "1640",
      },
    },
    "Past tense 3": {
      "selected": false,
      "lsWord": {
        "83 [eighty-three]": "1641",
        "Past tense 3": "1642",
        "to make a call": "1643",
        "I made a call.": "1644",
        "I was talking on the phone all the time.": "1645",
        "to ask": "1646",
        "I asked.": "1647",
        "I always asked.": "1648",
        "to narrate": "1649",
        "I narrated.": "1650",
        "I narrated the whole story.": "1651",
        "to study": "1652",
        "I studied.": "1653",
        "I studied the whole evening.": "1654",
        "to work": "1655",
        "I worked.": "1656",
        "I worked all day long.": "1657",
        "to eat": "1658",
        "I ate.": "1659",
        "I ate all the food.": "1660",
      },
    },
    "Past tense 4": {
      "selected": false,
      "lsWord": {
        "84 [eighty-four]": "1661",
        "Past tense 4": "1662",
        "to read": "1663",
        "I read.": "1664",
        "I read the whole novel.": "1665",
        "to understand": "1666",
        "I understood.": "1667",
        "I understood the whole text.": "1668",
        "to answer": "1669",
        "I answered.": "1670",
        "I answered all the questions.": "1671",
        "I know that � I knew that.": "1672",
        "I write that � I wrote that.": "1673",
        "I hear that � I heard that.": "1674",
        "I�ll get it � I got it.": "1675",
        "I�ll bring that � I brought that.": "1676",
        "I�ll buy that � I bought that.": "1677",
        "I expect that � I expected that.": "1678",
        "I�ll explain that � I explained that.": "1679",
      },
    },
    "Questions � Past tense 1": {
      "selected": false,
      "lsWord": {
        "85 [eighty-five]": "1681",
        "Questions � Past tense 1": "1682",
        "How much did you drink?": "1683",
        "How much did you work?": "1684",
        "How much did you write?": "1685",
        "How did you sleep?": "1686",
        "How did you pass the exam?": "1687",
        "How did you find the way?": "1688",
        "Who did you speak to?": "1689",
        "With whom did you make an appointment?": "1690",
        "With whom did you celebrate your birthday?": "1691",
        "Where were you?": "1692",
        "Where did you live?": "1693",
        "Where did you work?": "1694",
        "What did you suggest?": "1695",
        "What did you eat?": "1696",
        "What did you come to know?": "1697",
        "How fast did you drive?": "1698",
        "How long did you fly?": "1699",
        "How high did you jump?": "1700",
      },
    },
    "Questions � Past tense 2": {
      "selected": false,
      "lsWord": {
        "86 [eighty-six]": "1701",
        "Questions � Past tense 2": "1702",
        "Which tie did you wear?": "1703",
        "Which car did you buy?": "1704",
        "Which newspaper did you subscribe to?": "1705",
        "Who did you see?": "1706",
        "Who did you meet?": "1707",
        "Who did you recognize?": "1708",
        "When did you get up?": "1709",
        "When did you start?": "1710",
        "When did you finish?": "1711",
        "Why did you wake up?": "1712",
        "Why did you become a teacher?": "1713",
        "Why did you take a taxi?": "1714",
        "Where did you come from?": "1715",
        "Where did you go?": "1716",
        "Where were you?": "1717",
        "Who did you help?": "1718",
        "Who did you write to?": "1719",
        "Who did you reply to?": "1720",
      },
    },
    "Past tense of modal verbs 1": {
      "selected": false,
      "lsWord": {
        "87 [eighty-seven]": "1721",
        "Past tense of modal verbs 1": "1722",
        "We had to water the flowers.": "1723",
        "We had to clean the apartment.": "1724",
        "We had to wash the dishes.": "1725",
        "Did you have to pay the bill?": "1726",
        "Did you have to pay an entrance fee?": "1727",
        "Did you have to pay a fine?": "1728",
        "Who had to say goodbye?": "1729",
        "Who had to go home early?": "1730",
        "Who had to take the train?": "1731",
        "We did not want to stay long.": "1732",
        "We did not want to drink anything.": "1733",
        "We did not want to disturb you.": "1734",
        "I just wanted to make a call.": "1735",
        "I just wanted to call a taxi.": "1736",
        "Actually I wanted to drive home.": "1737",
        "I thought you wanted to call your wife.": "1738",
        "I thought you wanted to call information.": "1739",
        "I thought you wanted to order a pizza.": "1740",
      },
    },
    "Past tense of modal verbs 2": {
      "selected": false,
      "lsWord": {
        "88 [eighty-eight]": "1741",
        "Past tense of modal verbs 2": "1742",
        "My son did not want to play with the doll.": "1743",
        "My daughter did not want to play football / soccer (am.).": "1744",
        "My wife did not want to play chess with me.": "1745",
        "My children did not want to go for a walk.": "1746",
        "They did not want to tidy the room.": "1747",
        "They did not want to go to bed.": "1748",
        "He was not allowed to eat ice cream.": "1749",
        "He was not allowed to eat chocolate.": "1750",
        "He was not allowed to eat sweets.": "1751",
        "I was allowed to make a wish.": "1752",
        "I was allowed to buy myself a dress.": "1753",
        "I was allowed to take a chocolate.": "1754",
        "Were you allowed to smoke in the airplane?": "1755",
        "Were you allowed to drink beer in the hospital?": "1756",
        "Were you allowed to take the dog into the hotel?": "1757",
        "During the holidays the children were allowed to remain outside late.": "1758",
        "They were allowed to play in the yard for a long time.": "1759",
        "They were allowed to stay up late.": "1760",
      },
    },
    "Imperative 1": {
      "selected": false,
      "lsWord": {
        "89 [eighty-nine]": "1761",
        "Imperative 1": "1762",
        "You are so lazy � don�t be so lazy!": "1763",
        "You sleep for so long � don�t sleep so late!": "1764",
        "You come home so late � don�t come home so late!": "1765",
        "You laugh so loudly � don�t laugh so loudly!": "1766",
        "You speak so softly � don�t speak so softly!": "1767",
        "You drink too much � don�t drink so much!": "1768",
        "You smoke too much � don�t smoke so much!": "1769",
        "You work too much � don�t work so much!": "1770",
        "You drive too fast � don�t drive so fast!": "1771",
        "Get up, Mr. Miller!": "1772",
        "Sit down, Mr. Miller!": "1773",
        "Remain seated, Mr. Miller!": "1774",
        "Be patient!": "1775",
        "Take your time!": "1776",
        "Wait a moment!": "1777",
        "Be careful!": "1778",
        "Be punctual!": "1779",
        "Don�t be stupid!": "1780",
      },
    },
    "Imperative 2": {
      "selected": false,
      "lsWord": {
        "90 [ninety]": "1781",
        "Imperative 2": "1782",
        "Shave!": "1783",
        "Wash yourself!": "1784",
        "Comb your hair!": "1785",
        "Call!": "1786",
        "Begin!": "1787",
        "Stop!": "1788",
        "Leave it!": "1789",
        "Say it!": "1790",
        "Buy it!": "1791",
        "Never be dishonest!": "1792",
        "Never be naughty!": "1793",
        "Never be impolite!": "1794",
        "Always be honest!": "1795",
        "Always be nice!": "1796",
        "Always be polite!": "1797",
        "Hope you arrive home safely!": "1798",
        "Take care of yourself!": "1799",
        "Do visit us again soon!": "1800",
      },
    },
    "Subordinate clauses: that 1": {
      "selected": false,
      "lsWord": {
        "91 [ninety-one]": "1801",
        "Subordinate clauses: that 1": "1802",
        "Perhaps the weather will get better tomorrow.": "1803",
        "How do you know that?": "1804",
        "I hope that it gets better.": "1805",
        "He will definitely come.": "1806",
        "Are you sure?": "1807",
        "I know that he�ll come.": "1808",
        "He�ll definitely call.": "1809",
        "Really?": "1810",
        "I believe that he�ll call.": "1811",
        "The wine is definitely old.": "1812",
        "Do you know that for sure?": "1813",
        "I think that it is old.": "1814",
        "Our boss is good-looking.": "1815",
        "Do you think so?": "1816",
        "I find him very handsome.": "1817",
        "The boss definitely has a girlfriend.": "1818",
        "Do you really think so?": "1819",
        "It is very possible that he has a girlfriend.": "1820",
      },
    },
    "Subordinate clauses: that 2": {
      "selected": false,
      "lsWord": {
        "92 [ninety-two]": "1821",
        "Subordinate clauses: that 2": "1822",
        "I�m angry that you snore.": "1823",
        "I�m angry that you drink so much beer.": "1824",
        "I�m angry that you come so late.": "1825",
        "I think he needs a doctor.": "1826",
        "I think he is ill.": "1827",
        "I think he is sleeping now.": "1828",
        "We hope that he marries our daughter.": "1829",
        "We hope that he has a lot of money.": "1830",
        "We hope that he is a millionaire.": "1831",
        "I heard that your wife had an accident.": "1832",
        "I heard that she is in the hospital.": "1833",
        "I heard that your car is completely wrecked.": "1834",
        "I�m happy that you came.": "1835",
        "I�m happy that you are interested.": "1836",
        "I�m happy that you want to buy the house.": "1837",
        "I�m afraid the last bus has already gone.": "1838",
        "I�m afraid we will have to take a taxi.": "1839",
        "I�m afraid I have no more money.": "1840",
      },
    },
    "Subordinate clauses: if": {
      "selected": false,
      "lsWord": {
        "93 [ninety-three]": "1841",
        "Subordinate clauses: if": "1842",
        "I don�t know if he loves me.": "1843",
        "I don�t know if he�ll come back.": "1844",
        "I don�t know if he�ll call me.": "1845",
        "Maybe he doesn�t love me?": "1846",
        "Maybe he won�t come back?": "1847",
        "Maybe he won�t call me?": "1848",
        "I wonder if he thinks about me.": "1849",
        "I wonder if he has someone else.": "1850",
        "I wonder if he lies.": "1851",
        "Maybe he thinks of me?": "1852",
        "Maybe he has someone else?": "1853",
        "Maybe he tells me the truth?": "1854",
        "I doubt whether he really likes me.": "1855",
        "I doubt whether he�ll write to me.": "1856",
        "I doubt whether he�ll marry me.": "1857",
        "Does he really like me?": "1858",
        "Will he write to me?": "1859",
        "Will he marry me?": "1860",
      },
    },
    "Conjunctions 1": {
      "selected": false,
      "lsWord": {
        "94 [ninety-four]": "1861",
        "Conjunctions 1": "1862",
        "Wait until the rain stops.": "1863",
        "Wait until I�m finished.": "1864",
        "Wait until he comes back.": "1865",
        "I�ll wait until my hair is dry.": "1866",
        "I�ll wait until the film is over.": "1867",
        "I�ll wait until the traffic light is green.": "1868",
        "When do you go on holiday?": "1869",
        "Before the summer holidays?": "1870",
        "Yes, before the summer holidays begin.": "1871",
        "Repair the roof before the winter begins.": "1872",
        "Wash your hands before you sit at the table.": "1873",
        "Close the window before you go out.": "1874",
        "When will you come home?": "1875",
        "After class?": "1876",
        "Yes, after the class is over.": "1877",
        "After he had an accident, he could not work anymore.": "1878",
        "After he had lost his job, he went to America.": "1879",
        "After he went to America, he became rich.": "1880",
      },
    },
    "Conjunctions 2": {
      "selected": false,
      "lsWord": {
        "95 [ninety-five]": "1881",
        "Conjunctions 2": "1882",
        "Since when is she no longer working?": "1883",
        "Since her marriage?": "1884",
        "Yes, she is no longer working since she got married.": "1885",
        "Since she got married, she�s no longer working.": "1886",
        "Since they have met each other, they are happy.": "1887",
        "Since they have had children, they rarely go out.": "1888",
        "When does she call?": "1889",
        "When driving?": "1890",
        "Yes, when she is driving.": "1891",
        "She calls while she drives.": "1892",
        "She watches TV while she irons.": "1893",
        "She listens to music while she does her work.": "1894",
        "I can�t see anything when I don�t have glasses.": "1895",
        "I can�t understand anything when the music is so loud.": "1896",
        "I can�t smell anything when I have a cold.": "1897",
        "We�ll take a taxi if it rains.": "1898",
        "We�ll travel around the world if we win the lottery.": "1899",
        "We�ll start eating if he doesn�t come soon.": "1900",
      },
    },
    "Conjunctions 3": {
      "selected": false,
      "lsWord": {
        "96 [ninety-six]": "1901",
        "Conjunctions 3": "1902",
        "I get up as soon as the alarm rings.": "1903",
        "I become tired as soon as I have to study.": "1904",
        "I will stop working as soon as I am 60.": "1905",
        "When will you call?": "1906",
        "As soon as I have a moment.": "1907",
        "He�ll call, as soon as he has a little time.": "1908",
        "How long will you work?": "1909",
        "I�ll work as long as I can.": "1910",
        "I�ll work as long as I am healthy.": "1911",
        "He lies in bed instead of working.": "1912",
        "She reads the newspaper instead of cooking.": "1913",
        "He is at the bar instead of going home.": "1914",
        "As far as I know, he lives here.": "1915",
        "As far as I know, his wife is ill.": "1916",
        "As far as I know, he is unemployed.": "1917",
        "I overslept; otherwise I�d have been on time.": "1918",
        "I missed the bus; otherwise I�d have been on time.": "1919",
        "I didn�t find the way / I got lost; otherwise I�d have been on time.": "1920",
      },
    },
    "Conjunctions 4": {
      "selected": false,
      "lsWord": {
        "97 [ninety-seven]": "1921",
        "Conjunctions 4": "1922",
        "He fell asleep although the TV was on.": "1923",
        "He stayed a while although it was late.": "1924",
        "He didn�t come although we had made an appointment.": "1925",
        "The TV was on. Nevertheless, he fell asleep.": "1926",
        "It was already late. Nevertheless, he stayed a while.": "1927",
        "We had made an appointment. Nevertheless, he didn�t come.": "1928",
        "Although he has no license, he drives the car.": "1929",
        "Although the road is slippery, he drives so fast.": "1930",
        "Although he is drunk, he rides his bicycle.": "1931",
        "Despite having no licence / license (am.), he drives the car.": "1932",
        "Despite the road being slippery, he drives fast.": "1933",
        "Despite being drunk, he rides the bike.": "1934",
        "Although she went to college, she can�t find a job.": "1935",
        "Although she is in pain, she doesn�t go to the doctor.": "1936",
        "Although she has no money, she buys a car.": "1937",
        "She went to college. Nevertheless, she can�t find a job.": "1938",
        "She is in pain. Nevertheless, she doesn�t go to the doctor.": "1939",
        "She has no money. Nevertheless, she buys a car.": "1940",
      },
    },
    "Double connectors": {
      "selected": false,
      "lsWord": {
        "98 [ninety-eight]": "1941",
        "Double connectors": "1942",
        "The journey was beautiful, but too tiring.": "1943",
        "The train was on time, but too full.": "1944",
        "The hotel was comfortable, but too expensive.": "1945",
        "He�ll take either the bus or the train.": "1946",
        "He�ll come either this evening or tomorrow morning.": "1947",
        "He�s going to stay either with us or in the hotel.": "1948",
        "She speaks Spanish as well as English.": "1949",
        "She has lived in Madrid as well as in London.": "1950",
        "She knows Spain as well as England.": "1951",
        "He is not only stupid, but also lazy.": "1952",
        "She is not only pretty, but also intelligent.": "1953",
        "She speaks not only German, but also French.": "1954",
        "I can neither play the piano nor the guitar.": "1955",
        "I can neither waltz nor do the samba.": "1956",
        "I like neither opera nor ballet.": "1957",
        "The faster you work, the earlier you will be finished.": "1958",
        "The earlier you come, the earlier you can go.": "1959",
        "The older one gets, the more complacent one gets.": "1960",
      },
    },
    "Genitive": {
      "selected": false,
      "lsWord": {
        "99 [ninety-nine]": "1961",
        "Genitive": "1962",
        "my girlfriend�s cat": "1963",
        "my boyfriend�s dog": "1964",
        "my children�s toys": "1965",
        "This is my colleague�s overcoat.": "1966",
        "That is my colleague�s car.": "1967",
        "That is my colleagues� work.": "1968",
        "The button from the shirt is gone.": "1969",
        "The garage key is gone.": "1970",
        "The boss� computer is not working.": "1971",
        "Who are the girl�s parents?": "1972",
        "How do I get to her parents� house?": "1973",
        "The house is at the end of the road.": "1974",
        "What is the name of the capital city of Switzerland?": "1975",
        "What is the title of the book?": "1976",
        "What are the names of the neighbour�s / neighbor�s (am.) children?": "1977",
        "When are the children�s holidays?": "1978",
        "What are the doctor�s consultation times?": "1979",
        "What time is the museum open?": "1980",
      },
    },
    "Adverbs": {
      "selected": false,
      "lsWord": {
        "100 [one hundred]": "1981",
        "Adverbs": "1982",
        "already � not yet": "1983",
        "Have you already been to Berlin?": "1984",
        "No, not yet.": "1985",
        "someone � no one": "1986",
        "Do you know someone here?": "1987",
        "No, I don�t know anyone here.": "1988",
        "a little longer � not much longer": "1989",
        "Will you stay here a little longer?": "1990",
        "No, I won�t stay here much longer.": "1991",
        "something else � nothing else": "1992",
        "Would you like to drink something else?": "1993",
        "No, I don�t want anything else.": "1994",
        "something already � nothing yet": "1995",
        "Have you already eaten something?": "1996",
        "No, I haven�t eaten anything yet.": "1997",
        "someone else � no one else": "1998",
        "Does anyone else want a coffee?": "1999",
        "No, no one else.": "2000",
      },
    }
  };

  static late int index;
  static late List<List<String>> lsAsso;
  static late SharedPreferences prefs;

  static void fillLsAsso() {
    lsAsso = [];
    index = 0;

    // fill lsAsso in order
    lsLesson.forEach((key, value) {
      Data.prefs.setBool(key, value["selected"] as bool);
      if (value["selected"] == true) {
        Map<String, String> lsWord = value["lsWord"] as Map<String, String>;
        lsWord.forEach((key, value) {
          lsAsso.add([key, value]);
        });
      }
    });

    // shuffle lsAsso
    lsAsso.shuffle();
  }

  static void init() async {
    // select lessons
    prefs = await SharedPreferences.getInstance();
    lsLesson.forEach((key, value) {
      if (Data.prefs.getBool(key) != null) {
        value["selected"] = Data.prefs.getBool(key) ?? false;
      }
      else {
        Data.prefs.setBool(key, value["selected"] as bool);
      }
    });

    Data.fillLsAsso();
  }
}